version: 2
jobs:
  build_frontend:
    docker:
      - image: node:8.11.2
    steps:
      - checkout
      - run:
          name: Greeting
          command: ls -la
      - run:
          name: Greeting
          command: echo $HOME
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_frontend
